version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "replica-bucket"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1c96qa9101eoo"
s3_prefix = "replica-bucket"
region = "eu-west-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
